source 'https://rubygems.org'
gem "dm-core"
gem "dm-migrations"
gem "dm-timestamps"
gem "sinatra"
gem "pgn", :git => "https://github.com/gauleng/pgn.git", :branch => "pgn-annotations"
gem "ferret"
# gem "sinatra-cross_origin", "~> 0.3.1"
gem "rack-cors"

# group :production do
	gem "dm-postgres-adapter"
# end